In [1]:
import nltk
#nltk.download('popular')

In [2]:
text = """

"""
tokens = nltk.word_tokenize(text)
tokens

['Metropolia',
 'University',
 'of',
 'Applied',
 'Sciences',
 'is',
 'one',
 'of',
 'the',
 'most',
 'international',
 'universities',
 'of',
 'applied',
 'sciences',
 'in',
 'Finland',
 '.',
 'Six',
 'international',
 'degree',
 'programmes',
 ',',
 'student',
 'and',
 'teacher',
 'mobility',
 ',',
 'work',
 'placement',
 'opportunities',
 'abroad',
 'and',
 'various',
 'projects',
 'play',
 'an',
 'essential',
 'role',
 'in',
 'the',
 'international',
 'activities',
 'at',
 'Metropolia',
 '.',
 'Over',
 '1,450',
 'foreign',
 'students',
 'representing',
 '90',
 'nationalities',
 'study',
 'in',
 'Metropolia',
 '.',
 'Some',
 '550',
 'Metropolitan',
 'students',
 'visit',
 'partner',
 'schools',
 'abroad',
 'as',
 'exchanges',
 'of',
 'over',
 '3',
 'months',
 'and',
 'about',
 '450',
 'exchange',
 'students',
 'come',
 'to',
 'Metropolia',
 '.',
 'Metropolia',
 'has',
 'over',
 '400',
 'partner',
 'universities',
 'around',
 'the',
 'world',
 '.']

In [3]:
tagged = nltk.pos_tag(tokens)
tagged

[('Metropolia', 'NNP'),
 ('University', 'NNP'),
 ('of', 'IN'),
 ('Applied', 'NNP'),
 ('Sciences', 'NNPS'),
 ('is', 'VBZ'),
 ('one', 'CD'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('most', 'RBS'),
 ('international', 'JJ'),
 ('universities', 'NNS'),
 ('of', 'IN'),
 ('applied', 'JJ'),
 ('sciences', 'NNS'),
 ('in', 'IN'),
 ('Finland', 'NNP'),
 ('.', '.'),
 ('Six', 'NNP'),
 ('international', 'JJ'),
 ('degree', 'NN'),
 ('programmes', 'NNS'),
 (',', ','),
 ('student', 'NN'),
 ('and', 'CC'),
 ('teacher', 'NN'),
 ('mobility', 'NN'),
 (',', ','),
 ('work', 'NN'),
 ('placement', 'NN'),
 ('opportunities', 'NNS'),
 ('abroad', 'RB'),
 ('and', 'CC'),
 ('various', 'JJ'),
 ('projects', 'NNS'),
 ('play', 'VBP'),
 ('an', 'DT'),
 ('essential', 'JJ'),
 ('role', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('international', 'JJ'),
 ('activities', 'NNS'),
 ('at', 'IN'),
 ('Metropolia', 'NNP'),
 ('.', '.'),
 ('Over', 'IN'),
 ('1,450', 'CD'),
 ('foreign', 'JJ'),
 ('students', 'NNS'),
 ('representing', 'VBG'),
 ('90', 'CD'),
 ('nationalities', 'NNS'),
 ('study', 'VBP'),
 ('in', 'IN'),
 ('Metropolia', 'NNP'),
 ('.', '.'),
 ('Some', 'DT'),
 ('550', 'CD'),
 ('Metropolitan', 'JJ'),
 ('students', 'NNS'),
 ('visit', 'VBP'),
 ('partner', 'NN'),
 ('schools', 'NNS'),
 ('abroad', 'RB'),
 ('as', 'IN'),
 ('exchanges', 'NNS'),
 ('of', 'IN'),
 ('over', 'IN'),
 ('3', 'CD'),
 ('months', 'NNS'),
 ('and', 'CC'),
 ('about', 'IN'),
 ('450', 'CD'),
 ('exchange', 'NN'),
 ('students', 'NNS'),
 ('come', 'VBP'),
 ('to', 'TO'),
 ('Metropolia', 'NNP'),
 ('.', '.'),
 ('Metropolia', 'NNP'),
 ('has', 'VBZ'),
 ('over', 'RP'),
 ('400', 'CD'),
 ('partner', 'NN'),
 ('universities', 'NNS'),
 ('around', 'IN'),
 ('the', 'DT'),
 ('world', 'NN'),
 ('.', '.')]

In [4]:
grammar = "Name: {(<NNP|NNPS>+<IN>*<NNP|NNPS>+)|<NNP|NNPS>+}"
chunk_parser = nltk.RegexpParser(grammar)
tree = chunk_parser.parse(tagged)
tree.draw()